### ISSUE TITLE
Digitally controlled firmware state rather than physical 

### ISSUE THREAD

**Issue by Matthewseffects** [TheKikGen/USBMidiKliK#10]
Hi!

I'm wanting to switch between firmware's based on a command i can send to the 16u2.
So normally it shows up as a midi controller but when i hit "Update" on my custom avrdude program it switches the firmware on the 16u2 and then updates my 4809 to the latest code and then switches back to the midi firmware.
is this doable with your code?

**Comment by TheKikGen** [comment]
If you need to update the Arduino firmware without positionnig a jumper, you can  send this sysex that will reboot the device in serial mode, until the next boot.

 F0 77 77 77 09 F7
