### ISSUE TITLE
usb host

### ISSUE THREAD

**Issue by denia85** [TheKikGen/USBMidiKliK#12]
Does this scheme work as a usb host?

**Comment by orzdk** [comment]
No, this is a USB Device, - not host. To implement a host you need something like https://github.com/felis/USB_Host_Shield_2.0 and an AliExpress/Ebay USB Mini Host Shield or similar.

**Comment by TheKikGen** [comment]
For USB Host converter, you can check my other project here : https://github.com/TheKikGen/KonverterMidiUSB/blob/master/README.md
