### ISSUE TITLE
I do not know how to generate Mega hex file

### ISSUE THREAD

**Issue by luca-art** [TheKikGen/USBMidiKliK#13]
Hi and thank you for your code.
I made a Jupiter-8 (Arturia plugin) controller over a MEGA. Everything works fine when I tried your software over an UNO (reset Arduino, Atmel Flip, etc) but now, i have to inject it over the MEGA and I do not know how can i do it. I do not have hex file for MEGA and I do notknow how compilate it. I read #8 post and I spent half of the morning figuring out the way to do it, but I am not capable. Is it a process involving the command line? I am a newby in programing. Thank you

**Comment by luca-art** [comment]
Anybody Knows?

**Comment by TheKikGen** [comment]
Install the Arduino IDE and compile/upload  for the Mega.
