### ISSUE TITLE
Uno with 16u2 is detected as a COM port from time to time after firmware is uploaded.

### ISSUE THREAD

**Issue by foo4bar** [TheKikGen/USBMidiKliK#18]
I.e., one time I connect it via USB to a laptop running Win10, it may be detected as a COM port, and either TX or RX led is lit at the same time. The next time I connect it, it may be detected as a midi device. Behavior is random.

When Uno is detected as a midi device, firmware works fine. Thank you for your work :)

**Comment by foo4bar** [comment]
Checked my board with a Linux machine as well, and everything's OK. So, I suppose, Win10 generates some weird USB traffic that's often recognized as the sysex message to enable serial boot mode. Will build the firmware without dual mode and try again. If everything's OK on Win10 after that, then my supposition re strange USB traffic is right.

**Comment by foo4bar** [comment]
Have built the firmware with the [line](https://github.com/TheKikGen/USBMidiKliK/blob/49fb4aaafc8795fbe8a9bb4803edadc86228ba65/USBMidiKliK_dual.cpp#L877) commented out. Everything's fine on Win10 now. So, my supposition above re sysex is right.

**Comment by foo4bar** [comment]
Have built the firmware with the [line](https://github.com/TheKikGen/USBMidiKliK/blob/49fb4aaafc8795fbe8a9bb4803edadc86228ba65/USBMidiKliK_dual.cpp#L877) commented out. Everything's fine on Win10 now. So, my supposition above re sysex is right.

**Comment by TheKikGen** [comment]
USB within Windows is sometimes  temperamental !
You can gon in the Device manager, show hidden devices, and delete every com ports and midi devices you see related with USB MidiKlik/Arduino, then reboot your computer.
