### ISSUE TITLE
Lost first vendor Id nibble n1 on change settings

### ISSUE THREAD

**Issue by margat78** [TheKikGen/USBMidiKliK#20]
I'm trying to send:

F077 7777 0C08 0F01 0309 0006 08F7
Vendor Id:8F13
Product Id : 9068

Mac osx recognize device as:

ID product: 0x9068
ID vendor: 0xF139

**Comment by TheKikGen** [comment]
F077 7777 0C      **08    0F   01    03 09  00 06 08** F7
Have a look in the code directly. 
https://github.com/TheKikGen/USBMidiKliK/blob/555111e9de0d16ed67f9fa9746b9d6a4763be94f/USBMidiKliK_dual.cpp#L1050

**Comment by TheKikGen** [comment]
`EEPROM_Params.vendorID = GetInt16FromHex4Bin((char *) &sysExInternalBuffer[3]);  `

should be probably 

`EEPROM_Params.vendorID = GetInt16FromHex4Bin((char *) &sysExInternalBuffer[2]);`

**Comment by TheKikGen** [comment]
NB : this was fixed in the last code version.
