### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by steeley** [TheKikGen/USBMidiKliK#22]
Sorry if this is the wrong place but I cannot get this script working on. OSX:
https://github.com/TheKikGen/USBMidiKliK/pull/7

I have fish v3.40 install from homebrew, so the only thing I have changed is the fish path in init.fish to:
/usr/local/bin/fish

The script runs but produces the following error:

`./scripts/init.fish
readlink: illegal option -- m
usage: readlink [-n] [file ...]
usage: dirname path
readlink: illegal option -- m
usage: readlink [-n] [file ...]
usage: dirname path
mkdir: /dependencies: Read-only file system
ERROR while downloading 'https://github.com/EsGeh/git_deps/raw/755daa23dd0b17cc986d4a1339e93ef5ec621fc7/get_deps.fish'
`

Any help appreciated
TIA

**Comment by TheKikGen** [comment]
How to compile is here :
https://github.com/TheKikGen/USBMidiKliK/wiki
