### ISSUE TITLE
Changing device name

### ISSUE THREAD

**Issue by asterow** [TheKikGen/USBMidiKliK#4]
Hi,

First i want to thank you for all your work, it's great !! 

I tried to change the name of the midi device without success.
the name is stuck to USA MidiKliK Build-646

- I edit the makefile and build a new .hex file (i see -DMIDI_DEVICE_PRODUCT_STRING="USA Miditest Build-654                       " in compilation log)
- I connect my Arduino Uno R3 in DFU mode and upload the new .hex file with 
  > sudo dfu-programmer atmega16u2 erase
  > dfu-programmer atmega16u2 flash USBMidiKliK_dual.hex
  > dfu-programmer atmega16u2 reset
- I disconnect / reconnect the Arduino but the name is still USA MidiKliK Build-646

- I tried to upload the sketch midiUsbConverter.ino and call SetProductString() in the setup()

- I tried to use the OSX app SysExLibrarian (https://www.snoize.com/SysExLibrarian/) to upload the sysex of your readme (F0 77 77 77 0B 55 53 42 20 4D 69 64 69 4B 6C 69 4B F7) and reboot the Arduino

In all cases, device name is still "USA MidiKliK Build-646"

Do you have any idea of what is causing this ? Thanks you very much for you help

**Comment by TheKikGen** [comment]
As said in the readme, You must change the name from SERIAL MIDI DIN.  USB is not available at the moment for internal sysex.
So you must plug a cable from your Arduino MIDI DIN OUT to Arduino MIDI DIN IN (make a loop), select the MIDI OUT serial from SysExLibrarian, then send the bytes sequence, that will go to the MIDI jack IN.


Not that the last release is 650.  
Hex file is already available.

**Comment by TheKikGen** [comment]
Issue closed.

**Comment by TheKikGen** [comment]
Uninstalling the device in the device manager, disconnect, and reconnect the board can help also.

**Comment by TheKikGen** [comment]
USB internal SYSEX are available since build 884.
